//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kosPU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class account_ownerr
    {
        public int owner_id { get; set; }
        public string name_owner { get; set; }
        public string email_owner { get; set; }
        public string username_owner { get; set; }
        public string password_owner { get; set; }
        public int group_owner { get; set; }
        public string address_owner { get; set; }
        public string phone_owner { get; set; }
        public string gender_owner { get; set; }
        public Nullable<System.DateTime> createddate_owner { get; set; }
    }
}
